# Generated by Django 4.2.6 on 2023-12-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidtube', '0002_account_delete_channel_delete_uploadmod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dp',
            field=models.ImageField(default='tom.png', upload_to='C:\\Users\\sures\\OneDrive\\Documents\\python\\django\\youtube_clone\\static\\images'),
        ),
        migrations.AddField(
            model_name='account',
            name='id_user',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
