# Generated by Django 4.2.6 on 2024-01-03 18:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vidtube', '0003_account_dp_account_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('thumb', models.ImageField(default='thumbnail1.png', upload_to='C:\\Users\\sures\\OneDrive\\Documents\\python\\django\\youtube_clone\\static\\images\\thumbnails')),
                ('likes', models.IntegerField(default=0)),
                ('des', models.CharField(max_length=150)),
                ('views', models.IntegerField(default=0)),
                ('sub', models.IntegerField(default=0)),
            ],
        ),
    ]
