# Generated by Django 4.2.6 on 2024-01-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidtube', '0005_alter_post_thumb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['?']},
        ),
        migrations.AlterField(
            model_name='account',
            name='dp',
            field=models.ImageField(default='tom.png', upload_to='C:\\Users\\sures\\OneDrive\\Documents\\python\\django\\youtube_clone\\media'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumb',
            field=models.ImageField(default='thumbnail1.png', upload_to='C:\\Users\\sures\\OneDrive\\Documents\\python\\django\\youtube_clone\\media'),
        ),
    ]
