# Generated by Django 4.2.6 on 2024-01-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidtube', '0009_post_dat_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('acc_id', models.CharField(max_length=150)),
            ],
        ),
    ]
